# Generated by Django 3.2.6 on 2021-08-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=150, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('genere', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
                ('writer', models.CharField(blank=True, max_length=150, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.URLField(blank=True, max_length=255, null=True)),
                ('metascore', models.FloatField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=150, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('dvd', models.DateField(blank=True, null=True)),
                ('box_office', models.CharField(blank=True, max_length=150, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
